import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { Award, CheckCircle2, ChevronDown, HeartHandshake, MapPin, Medal, RefreshCw, Search, Settings2, ShieldCheck, Sparkles, Trophy, UserRound, X } from "lucide-react";
import { GiverBoardPeriod, RankedGiver, useGiverBoard } from "../../hooks/usePortfolio";

type VisibilityFilter = "all" | "verified";
const medalStyles = ["bg-amber-100 text-amber-700 ring-amber-200", "bg-slate-100 text-slate-600 ring-slate-200", "bg-orange-100 text-orange-700 ring-orange-200"];

function GiverAvatar({ giver, prominent = false }: { giver: RankedGiver; prominent?: boolean }) {
  const size = prominent ? "h-14 w-14" : "h-10 w-10";
  return <div className="relative shrink-0">
    {giver.isAnonymous ? <span className={`${size} flex items-center justify-center rounded-2xl bg-purple-100 text-helpMe-700`}><UserRound className={prominent ? "h-7 w-7" : "h-5 w-5"} /></span>
      : giver.user.profileImg ? <img src={giver.user.profileImg} alt="" className={`${size} rounded-2xl object-cover`} />
      : <span className={`${size} flex items-center justify-center rounded-2xl bg-gradient-to-br from-pink-100 to-purple-200 font-black text-helpMe-800`}>{giver.user.name.charAt(0)}</span>}
    {giver.isVerified && <span className="absolute -bottom-1 -right-1 rounded-full bg-white p-0.5 text-emerald-600" title="Verified member"><CheckCircle2 className="h-4 w-4" fill="currentColor" strokeWidth={2.5} /></span>}
  </div>;
}

function GiverIdentity({ giver, prominent = false }: { giver: RankedGiver; prominent?: boolean }) {
  return <div className="flex min-w-0 items-center gap-3"><GiverAvatar giver={giver} prominent={prominent} /><div className="min-w-0"><p className={`${prominent ? "text-base" : "text-sm"} truncate font-bold text-gray-950`}>{giver.user.name}</p><p className="mt-0.5 flex items-center gap-1 truncate text-xs text-gray-500">{giver.location ? <><MapPin className="h-3 w-3" />{giver.location}</> : "Private profile"}</p></div></div>;
}

function TopGiver({ giver }: { giver: RankedGiver }) {
  const className = "group relative overflow-hidden rounded-2xl border border-gray-200 bg-white p-4 shadow-sm transition duration-200 hover:-translate-y-0.5 hover:border-helpMe-200 hover:shadow-md focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-helpMe-500 sm:p-5";
  const content = <>{giver.rank === 1 && <div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-amber-300 via-pink-400 to-helpMe-600" />}<div className="flex items-start justify-between gap-3"><GiverIdentity giver={giver} prominent /><span className={`flex h-8 min-w-8 shrink-0 items-center justify-center rounded-lg px-2 text-xs font-black ring-1 ${medalStyles[giver.rank - 1]}`}>#{giver.rank}</span></div><div className="mt-5 flex items-end justify-between gap-3"><div className="flex gap-3 text-xs text-gray-500"><span><strong className="text-gray-900">{giver.helpCount}</strong> helps</span><span><strong className="text-gray-900">{giver.giveawayCount}</strong> gifts</span></div><div className="text-right"><p className="text-2xl font-black leading-none tracking-tight text-helpMe-950">{giver.points.toLocaleString()}</p><p className="mt-1 text-[9px] font-bold uppercase tracking-[0.13em] text-gray-400">points</p></div></div></>;
  return giver.isAnonymous || giver.isDemo ? <article className={className}>{content}</article> : <Link to={`/u/${encodeURIComponent(giver.user.name)}`} className={className}>{content}</Link>;
}

function RankingRow({ giver }: { giver: RankedGiver }) {
  const className = "group flex items-center gap-3 border-t border-gray-100 px-4 py-3 transition hover:bg-helpMe-50/50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-[-2px] focus-visible:outline-helpMe-500 sm:px-5";
  const content = <><span className="w-8 shrink-0 text-center text-xs font-black text-gray-400 sm:w-10">#{giver.rank}</span><div className="min-w-0 flex-1"><GiverIdentity giver={giver} /></div><p className="hidden w-20 shrink-0 text-center text-sm font-semibold text-gray-700 sm:block">{giver.helpCount}</p><p className="hidden w-20 shrink-0 text-center text-sm font-semibold text-gray-700 sm:block">{giver.giveawayCount}</p><div className="w-20 shrink-0 text-right sm:w-24"><p className="text-sm font-black text-helpMe-900">{giver.points.toLocaleString()}</p><p className="text-[9px] uppercase tracking-wider text-gray-400 sm:hidden">points</p></div></>;
  return giver.isAnonymous || giver.isDemo ? <div className={className}>{content}</div> : <Link to={`/u/${encodeURIComponent(giver.user.name)}`} className={className}>{content}</Link>;
}

function LoadingState() {
  return <div className="space-y-5" aria-label="Loading Givers-board"><div className="grid gap-3 md:grid-cols-3">{[1, 2, 3].map((item) => <div key={item} className="h-36 animate-pulse rounded-2xl bg-gray-200" />)}</div><div className="h-56 animate-pulse rounded-2xl bg-gray-200" /></div>;
}

export default function GiverBoard() {
  const [period, setPeriod] = useState<GiverBoardPeriod>("month");
  const [query, setQuery] = useState("");
  const [visibility, setVisibility] = useState<VisibilityFilter>("all");
  const { data, isLoading, isError, refetch, isFetching } = useGiverBoard(period);
  const normalizedQuery = query.trim().toLowerCase();
  const topThree = (data?.givers || []).slice(0, 3);
  const ranked = useMemo(() => (data?.givers || []).filter((giver) => {
    const matchesQuery = !normalizedQuery || giver.user.name.toLowerCase().includes(normalizedQuery) || giver.location.toLowerCase().includes(normalizedQuery);
    return matchesQuery && (visibility === "all" || giver.isVerified);
  }), [data?.givers, normalizedQuery, visibility]);
  const hasFilters = Boolean(normalizedQuery) || visibility !== "all";
  const listGivers = hasFilters ? ranked : ranked.filter((giver) => giver.rank > 3);

  return <main className="min-h-screen bg-[#f8f7fa] pt-[68px] sm:pt-[76px]">
    <section className="relative overflow-hidden bg-helpMe-950 text-white"><div className="pointer-events-none absolute -left-10 top-0 h-52 w-52 rounded-full bg-pink-500/20 blur-[90px]" /><div className="pointer-events-none absolute right-0 top-0 h-64 w-64 rounded-full bg-purple-400/15 blur-[100px]" /><div className="relative mx-auto flex max-w-7xl flex-col gap-7 px-5 py-10 sm:px-8 sm:py-12 lg:flex-row lg:items-center lg:justify-between"><div className="max-w-2xl"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.12em] text-pink-200"><Sparkles className="h-3.5 w-3.5" /> Community recognition</div><h1 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Givers-board</h1><p className="mt-2 max-w-xl text-sm leading-6 text-purple-100/75">Celebrating completed support and the people creating measurable community impact.</p></div><div className="grid grid-cols-2 gap-3"><div className="flex min-w-36 items-center gap-3 rounded-2xl border border-white/10 bg-white/10 px-4 py-4 backdrop-blur"><HeartHandshake className="h-5 w-5 text-pink-300" /><div><p className="text-2xl font-black leading-none">{data?.summary.totalGivers ?? 0}</p><p className="mt-1.5 text-[10px] text-purple-100/65">Givers ranked</p></div></div><div className="flex min-w-36 items-center gap-3 rounded-2xl border border-white/10 bg-white/10 px-4 py-4 backdrop-blur"><Award className="h-5 w-5 text-amber-300" /><div><p className="text-2xl font-black leading-none">{data?.summary.totalImpactActions ?? 0}</p><p className="mt-1.5 text-[10px] text-purple-100/65">Impact actions</p></div></div></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-8 sm:px-8 sm:py-10">
      <div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-50 text-amber-600"><Trophy className="h-5 w-5" /></div><div><h2 className="font-black text-gray-950">Community rankings</h2><p className="text-xs text-gray-500">100 points per completed help or funded giveaway</p></div></div>
      <div className="giver-board-toolbar mt-5 flex flex-col gap-2 rounded-2xl border border-gray-200 bg-white p-3 shadow-sm"><label className="relative block min-w-0 flex-1"><span className="sr-only">Search ranked givers</span><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search givers or location" className="h-11 w-full rounded-xl border border-gray-200 bg-gray-50 pl-9 pr-9 text-sm outline-none transition placeholder:text-gray-400 focus:border-helpMe-400 focus:bg-white focus:ring-2 focus:ring-helpMe-100" />{query && <button type="button" onClick={() => setQuery("")} aria-label="Clear search" className="absolute right-2.5 top-1/2 -translate-y-1/2 rounded p-1 text-gray-400 hover:text-gray-700"><X className="h-3.5 w-3.5" /></button>}</label><div className="inline-flex h-11 shrink-0 rounded-xl bg-gray-100 p-1" aria-label="Leaderboard period">{([['month', 'This month'], ['all', 'All time']] as const).map(([value, label]) => <button key={value} type="button" onClick={() => setPeriod(value)} aria-pressed={period === value} className={`flex-1 rounded-lg px-4 text-xs font-bold transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-helpMe-500 md:flex-none ${period === value ? "bg-white text-helpMe-900 shadow-sm" : "text-gray-500 hover:text-gray-900"}`}>{label}</button>)}</div><button type="button" onClick={() => setVisibility((current) => current === "all" ? "verified" : "all")} aria-pressed={visibility === "verified"} className={`inline-flex h-11 shrink-0 items-center justify-center gap-2 rounded-xl border px-4 text-xs font-bold transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-helpMe-500 ${visibility === "verified" ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-gray-200 bg-white text-gray-600 hover:border-gray-300"}`}><ShieldCheck className="h-4 w-4" /> Verified only</button></div>
      <details className="group mt-4 rounded-xl border border-gray-200 bg-white px-4 py-3 text-xs text-gray-600"><summary className="flex cursor-pointer list-none items-center justify-between font-semibold text-gray-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-helpMe-500"><span>How rankings and privacy work</span><ChevronDown className="h-4 w-4 transition group-open:rotate-180" /></summary><p className="mt-3 max-w-3xl leading-5">Only verified impact counts. Gift amounts never affect rank, and members can hide their identity from the board in Account settings. Anonymous donations stay excluded from public scores.</p></details>
      {data?.isDemo && <div className="mt-4 flex items-center gap-2 rounded-xl bg-amber-50 px-4 py-2.5 text-xs text-amber-900 ring-1 ring-amber-200"><Sparkles className="h-3.5 w-3.5 shrink-0" /><p><strong>Preview data:</strong> sample rankings disappear when real qualifying activity is recorded.</p></div>}
      <div className="mt-5">{isLoading ? <LoadingState /> : isError ? <div className="rounded-2xl border border-rose-200 bg-white px-6 py-12 text-center shadow-sm"><RefreshCw className="mx-auto h-7 w-7 text-rose-400" /><h3 className="mt-3 font-bold text-gray-900">Rankings are unavailable</h3><button type="button" onClick={() => refetch()} disabled={isFetching} className="mt-4 rounded-xl bg-helpMe-900 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-60">Try again</button></div> : !data?.givers.length ? <div className="rounded-2xl border border-gray-200 bg-white px-6 py-12 text-center"><Medal className="mx-auto h-8 w-8 text-helpMe-500" /><h3 className="mt-3 text-lg font-black text-gray-950">First place is open</h3><p className="mx-auto mt-2 max-w-md text-sm text-gray-500">Complete a public help or fund a monetary giveaway to earn 100 impact points.</p><Link to="/all-help-requests" className="mt-5 inline-flex rounded-xl bg-helpMe-900 px-4 py-2.5 text-sm font-bold text-white">Explore requests</Link></div> : <>{!hasFilters && <div className="grid gap-3 md:grid-cols-3">{topThree.map((giver) => <TopGiver key={giver.user.id} giver={giver} />)}</div>}<div className={`${hasFilters || listGivers.length ? "mt-5" : "mt-0"} overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm`}><div className="flex items-center gap-3 bg-gray-50 px-4 py-2.5 text-[10px] font-bold uppercase tracking-wider text-gray-400 sm:px-5"><span className="w-8 shrink-0 text-center sm:w-10">Rank</span><span className="min-w-0 flex-1">Giver</span><span className="hidden w-20 shrink-0 text-center sm:block">Helps</span><span className="hidden w-20 shrink-0 text-center sm:block">Gifts</span><span className="w-20 shrink-0 text-right sm:w-24">Points</span></div>{listGivers.length ? listGivers.map((giver) => <RankingRow key={giver.user.id} giver={giver} />) : <div className="px-5 py-8 text-center text-sm text-gray-500">{hasFilters ? "No ranked giver matches these filters." : "No additional ranked givers yet."}</div>}</div></>}</div>
      <div className="mt-5 flex flex-col gap-3 rounded-2xl bg-helpMe-950 px-5 py-4 text-white sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold">Control your board visibility</p><p className="mt-0.5 text-xs text-purple-100/70">Hide your identity while keeping your impact recognized.</p></div><Link to="/dashboard?tab=giver-board" className="inline-flex w-fit items-center gap-2 rounded-lg bg-white/10 px-3 py-2 text-xs font-bold ring-1 ring-white/15 transition hover:bg-white/15"><Settings2 className="h-4 w-4" /> Privacy settings</Link></div>
    </section>
  </main>;
}
